name: one_page
description: Clone of a bootstrap template from bootstrap_made website in flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animations: 
  carousel_slider: 
  cupertino_icons: 
  flutter:
    sdk: flutter
  flutter_next:
    git:
      url: https://github.com/shashiben/flutter_next.git
  flutter_svg: 
  go_router: 
  line_icons: 
  universal_html: 
  universal_platform: 
  url_launcher: 
  webviewx: 

dev_dependencies:
  build_runner: 
  flutter_launcher_icons:
  flutter_lints: 
  flutter_test:
    sdk: flutter
  preload: 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  web:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/clients/
    - assets/portfolio/
    - assets/team/
    - assets/testimonials/
    - assets/fonts/

  fonts:
    - family: Opensans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
